# Generated by Django 2.2.1 on 2021-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Url', models.CharField(max_length=256)),
                ('Phonenumber', models.IntegerField()),
            ],
        ),
    ]
